# Generated by Django 2.1.5 on 2019-04-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20190429_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
